# -*- coding: utf-8 -*-
"""CodigoEmPython

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hgtYIwlVx1lrykIbHTijwtkuR9g0-Rhl
"""

from datetime import datetime

class Banco:
    def __init__(self, nome=None, codigo_bacen=None):
        self.nome = nome
        self.codigo_bacen = codigo_bacen

class ContaBancaria:
    def __init__(self, agencia=None, numero_conta=None):
        self.agencia = agencia
        self.numero_conta = numero_conta
        self.__saldo = 0.0  # Atributo privado

    @property
    def saldo(self):
        return self.__saldo

class Transacao:
    def __init__(self):
        self._valor = 0.0
        self.data = None
        self.tipo = None
        self.conta_origem = None
        self.conta_destino = None

    @property
    def valor(self):
        return self._valor

    @valor.setter
    def valor(self, value):
        if value > 0:
            self._valor = value
        else:
            raise ValueError("O valor deve ser maior que 0")

# --- EXECUÇÃO (Equivalente ao Program.cs) ---

def main():
    meu_banco = Banco(nome="Banco do Brasil", codigo_bacen="001")
    minha_transacao = Transacao()

    try:
        # Tentando atribuir um valor negativo para testar a validação
        minha_transacao.valor = -250.00
        minha_transacao.data = datetime.now()
        minha_transacao.tipo = "PIX"
    except ValueError as e:
        print(f"Erro: {e}")

    print("\n--- REGISTRO BACEN ---")
    print(f"Banco: {meu_banco.nome}")
    print(f"Código: {meu_banco.codigo_bacen}")
    print("-----------------------")
    print(f"Tipo: {minha_transacao.tipo}")
    print(f"Valor: R$ {minha_transacao.valor:.2f}")
    print(f"Data: {minha_transacao.data}")

if __name__ == "__main__":
    main()

