# -*- coding: utf-8 -*-
"""CodigoEmPython

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hgtYIwlVx1lrykIbHTijwtkuR9g0-Rhl
"""

from datetime import datetime

class Banco:
    def __init__(self):
        self._nome = ""
        self._codigo_bacen = ""

    @property
    def nome(self):
        return self._nome.upper() if self._nome else ""

    @nome.setter
    def nome(self, value):
        self._nome = value

    @property
    def codigo_bacen(self):
        return self._codigo_bacen

    @codigo_bacen.setter
    def codigo_bacen(self, value):
        if not value or value.strip() == "":
            print("Erro: O Código BACEN não pode ser vazio ou nulo!")
        else:
            self._codigo_bacen = value

class Transacao:
    def __init__(self):
        self._valor = 0.0
        self.data = None
        self.tipo = ""

    @property
    def valor(self):
        return self._valor

    @valor.setter
    def valor(self, value):
        if value > 0:
            self._valor = value
        else:
            raise ValueError("O valor deve ser maior que 0")

def main():
    # Instância correta: meu_banco
    meu_banco = Banco()
    meu_banco.nome = "banco do brasil"
    meu_banco.codigo_bacen = ""  # Disparará o print de erro
    meu_banco.codigo_bacen = "001"

    minha_transacao = Transacao()

    try:
        minha_transacao.valor = 250.00
        minha_transacao.data = datetime.now()
        minha_transacao.tipo = "PIX"
    except ValueError as e:
        print(f"Erro: {e}")

    print("\n--- REGISTRO BACEN ---")
    print(f"Banco: {meu_banco.nome}")
    # Corrigido: de meu__banco para meu_banco
    print(f"Código: {meu_banco.codigo_bacen}")
    print("-----------------------")
    print(f"Tipo: {minha_transacao.tipo}")
    print(f"Valor: R$ {minha_transacao.valor:.2f}")
    print(f"Data: {minha_transacao.data}")

if __name__ == "__main__":
    main()

